[package]
name = "openmm-bindings"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bindgen = "0.60.1"
cmake = "0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bindgen = "0.60.1"
